#!/bin/bash

###############################################################################
# NFRA PIPELINE - MANUAL TEST COMMANDS
# 
# This file contains all commands to test the NFRA extraction pipeline.
# Run these commands in your local terminal to test the services and pipeline.
###############################################################################

echo "=========================================="
echo "NFRA EXTRACTION PIPELINE - TEST GUIDE"
echo "=========================================="
echo ""
echo "Follow these commands in order to test the entire flow:"
echo ""

# Section 1: Verify Environment
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║ STEP 1: Verify Python Environment                             ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Command to verify Python setup:"
echo ""
echo "  python --version"
echo "  pip list | grep -E 'requests|reportlab|PyMuPDF|python-dotenv|pyyaml'"
echo ""

# Section 2: Generate Sample PDF
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║ STEP 2: Generate Sample Financial PDF                         ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Command to create sample PDF with financial data:"
echo ""
echo "  python create_sample_pdf.py"
echo ""
echo "Expected output:"
echo "  ✓ Sample PDF created: sample_financial_report.pdf"
echo "  Size: sample_financial_report.pdf (~150KB)"
echo "  Contents: Balance Sheet, P&L, Compliance Notes, Auditor Report"
echo ""

# Section 3: Check Services
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║ STEP 3: Verify Remote Services are Running                     ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Command to check OCR service health:"
echo ""
echo "  curl -s http://34.47.203.146:8000/api/health | jq ."
echo ""
echo "Expected output:"
echo "  {"
echo "    \"status\": \"ok\","
echo "    \"gpu_name\": \"Tesla T4\","
echo "    \"gpu_memory\": {\"utilization_pct\": 9.7, ...}"
echo "  }"
echo ""
echo "Command to check LLM service health:"
echo ""
echo "  curl -s -X POST http://34.180.45.142:8000/api/extract \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"text\":\"test\",\"schema\":\"test\"}' | jq '.usage'"
echo ""
echo "Expected output:"
echo "  {"
echo "    \"input_tokens\": 58,"
echo "    \"output_tokens\": 2"
echo "  }"
echo ""

# Section 4: Pipeline Check
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║ STEP 4: Run Pipeline Connectivity Check                        ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Command to verify pipeline can reach both services:"
echo ""
echo "  python nfra/nfra_pipeline.py --check"
echo ""
echo "Expected output:"
echo "  Checking NFRA services..."
echo "    OCR Service: http://34.47.203.146:8000"
echo "    LLM Service: http://34.180.45.142:8000"
echo "    ✓ OCR Service: ok"
echo "    ✓ LLM Service: unknown"
echo "    ✓ All services operational"
echo ""

# Section 5: Process PDF - OCR Only
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║ STEP 5: Test OCR Extraction                                    ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Command to extract text from PDF using OCR service:"
echo ""
echo "  curl -s -X POST http://34.47.203.146:8000/api/ocr/batch \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d @- << 'EOF' | jq '.results[0] | keys' > /dev/null && echo 'OCR Success' || echo 'OCR Failed'"
echo "  {\"images\": [...]}"
echo "  EOF"
echo ""
echo "Or use direct Python:"
echo ""
echo "  python src/run_ocr.py sample_financial_report.pdf --url http://34.47.203.146:8000"
echo ""

# Section 6: Full Pipeline Test
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║ STEP 6: Run Full NFRA Pipeline (OCR + LLM Extraction)          ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Command to process PDF through complete pipeline:"
echo ""
echo "  python nfra/nfra_pipeline.py sample_financial_report.pdf \\"
echo "    --type 'Annual Report' \\"
echo "    --output nfra_extraction_result.json"
echo ""
echo "This performs:"
echo "  1. PDF → Images (via PyMuPDF)"
echo "  2. OCR extraction (Surya on 34.47.203.146:8000)"
echo "  3. LLM structured extraction (Qwen on 34.180.45.142:8000)"
echo "  4. Results saved to JSON"
echo ""
echo "Expected timing:"
echo "  - OCR extraction: 15-20 seconds (3 pages)"
echo "  - LLM extraction: 5-10 seconds"
echo "  - Total: 20-30 seconds"
echo ""

# Section 7: Review Results
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║ STEP 7: View Extraction Results                                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Command to view full results:"
echo ""
echo "  cat nfra_extraction_result.json | jq ."
echo ""
echo "Or view specific sections:"
echo ""
echo "  # Company Information"
echo "  cat nfra_extraction_result.json | jq '.extraction.result' | jq from_json"
echo ""
echo "  # OCR Text (first 500 chars)"
echo "  cat nfra_extraction_result.json | jq '.ocr.text' | cut -c1-500"
echo ""
echo "  # Token Usage"
echo "  cat nfra_extraction_result.json | jq '.extraction.usage'"
echo ""

# Section 8: Test with Different Document Types
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║ STEP 8: Test Other Document Types                             ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Test with different document types and save outputs:"
echo ""
echo "  # Balance Sheet"
echo "  python nfra/nfra_pipeline.py sample_financial_report.pdf \\"
echo "    --type 'Balance Sheet' \\"
echo "    --output results_balance_sheet.json"
echo ""
echo "  # Financial Statements"
echo "  python nfra/nfra_pipeline.py sample_financial_report.pdf \\"
echo "    --type 'Financial Statements' \\"
echo "    --output results_financial_statements.json"
echo ""
echo "  # Compliance Report"
echo "  python nfra/nfra_pipeline.py sample_financial_report.pdf \\"
echo "    --type 'Compliance Report' \\"
echo "    --output results_compliance.json"
echo ""

# Section 9: Monitor VM Services
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║ STEP 9: Monitor VM Services (Live Logs)                        ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Watch OCR service logs in real-time:"
echo ""
echo "  ssh tech@34.47.203.146 'tail -f ocr_service.log'"
echo ""
echo "Watch LLM service logs in real-time:"
echo ""
echo "  ssh tech@34.180.45.142 'tail -f llm_service.log'"
echo ""
echo "Check if services are still running:"
echo ""
echo "  ssh tech@34.47.203.146 'ps aux | grep python | grep -v grep'"
echo "  ssh tech@34.180.45.142 'ps aux | grep python | grep -v grep'"
echo ""

# Section 10: Troubleshooting
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║ TROUBLESHOOTING                                                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "If services are not responding:"
echo ""
echo "  # Restart OCR service:"
echo "  ssh tech@34.47.203.146 'pkill -f ocr_service.py && nohup python ocr_service.py > ocr_service.log 2>&1 &'"
echo ""
echo "  # Restart LLM service:"
echo "  ssh tech@34.180.45.142 'pkill -f llm_service.py && nohup python llm_service.py > llm_service.log 2>&1 &'"
echo ""
echo "If you get 'Connection refused':"
echo ""
echo "  # Check if VMs are reachable:"
echo "  ping 34.47.203.146"
echo "  ping 34.180.45.142"
echo ""
echo "If you get SSL warnings:"
echo ""
echo "  # This is safe to ignore - urllib3 compatibility issue with macOS SSL"
echo "  # Doesn't affect functionality"
echo ""

# Section 11: Summary
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║ QUICK TEST SEQUENCE                                            ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Run these 4 commands in sequence to test everything:"
echo ""
echo "  1. python create_sample_pdf.py"
echo ""
echo "  2. python nfra/nfra_pipeline.py --check"
echo ""
echo "  3. python nfra/nfra_pipeline.py sample_financial_report.pdf \\"
echo "       --type 'Annual Report' --output result.json"
echo ""
echo "  4. cat result.json | jq '.extraction' | jq from_json"
echo ""
echo "That's it! You should see structured financial data extracted."
echo ""
echo "=========================================="
echo "All tests completed!"
echo "=========================================="
